CREATE TABLE IF NOT EXISTS calendar_daily_raw (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    calendar_date DATE NOT NULL,
    market VARCHAR(30) NOT NULL,
    is_trading_day TINYINT NOT NULL,
    is_exchange_closed TINYINT NOT NULL,
    is_holiday TINYINT NOT NULL DEFAULT 0,
    holiday_name VARCHAR(100),
    pre_trade_date DATE,
    next_trade_date DATE,
    source_type VARCHAR(100) NOT NULL,
    source_url TEXT,
    available_time DATETIME NOT NULL,
    crawl_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    note TEXT,
    UNIQUE KEY uk_calendar_daily (calendar_date, market),
    KEY idx_calendar_market_date (market, calendar_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS event_calendar_raw (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    event_key VARCHAR(160) NOT NULL,
    event_layer VARCHAR(16) NOT NULL,
    event_type VARCHAR(50) NOT NULL,
    event_name VARCHAR(200) NOT NULL,
    country_region VARCHAR(30),
    scheduled_time DATETIME NOT NULL,
    actual_start_time DATETIME,
    actual_end_time DATETIME,
    is_confirmed TINYINT DEFAULT 0,
    importance INT,
    announcement_time DATETIME,
    available_time DATETIME NOT NULL,
    data_source VARCHAR(100) NOT NULL,
    source_url TEXT,
    crawl_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    note TEXT,
    UNIQUE KEY uk_event_calendar (event_key, scheduled_time),
    KEY idx_event_calendar_time (scheduled_time),
    KEY idx_event_calendar_layer (event_layer, scheduled_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS macro_release_raw (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    indicator_key VARCHAR(100) NOT NULL,
    indicator_name VARCHAR(160) NOT NULL,
    country_region VARCHAR(30) NOT NULL,
    frequency VARCHAR(20),
    period_date DATE NOT NULL,
    release_time DATETIME NOT NULL,
    actual_value DECIMAL(24,8),
    forecast_value DECIMAL(24,8),
    previous_value DECIMAL(24,8),
    revised_previous_value DECIMAL(24,8),
    unit VARCHAR(30),
    seasonal_adjustment VARCHAR(20),
    revision_no INT DEFAULT 0,
    is_preliminary TINYINT DEFAULT 0,
    available_time DATETIME NOT NULL,
    data_source VARCHAR(100) NOT NULL,
    source_url TEXT,
    crawl_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    raw_hash CHAR(64),
    note TEXT,
    UNIQUE KEY uk_macro_vintage (indicator_key, period_date, release_time, revision_no),
    KEY idx_macro_release_time (release_time),
    KEY idx_macro_indicator (indicator_key, period_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS global_market_daily (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    trade_date DATE NOT NULL,
    symbol VARCHAR(30) NOT NULL,
    symbol_name VARCHAR(100),
    asset_class VARCHAR(30) NOT NULL,
    open DECIMAL(24,8),
    high DECIMAL(24,8),
    low DECIMAL(24,8),
    close DECIMAL(24,8),
    settle DECIMAL(24,8),
    volume DECIMAL(24,4),
    currency VARCHAR(8),
    timezone VARCHAR(40),
    data_source VARCHAR(100) NOT NULL,
    source_url TEXT,
    available_time DATETIME NOT NULL,
    crawl_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    raw_hash CHAR(64),
    UNIQUE KEY uk_global_market (trade_date, symbol),
    KEY idx_global_symbol (symbol, trade_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
