CREATE TABLE IF NOT EXISTS cn_macro_political_event (
    event_id VARCHAR(80) NOT NULL,
    event_type VARCHAR(40) NOT NULL,
    event_name VARCHAR(255) NOT NULL,
    event_level VARCHAR(32) NOT NULL DEFAULT 'national',
    start_date DATE NOT NULL,
    end_date DATE NULL,
    publish_date DATE NULL,
    source_org VARCHAR(80) NULL,
    source_title VARCHAR(500) NULL,
    source_url VARCHAR(1000) NULL,
    source_text MEDIUMTEXT NULL,
    is_predicted TINYINT(1) NOT NULL DEFAULT 0,
    prediction_confidence DECIMAL(5,4) NOT NULL DEFAULT 1.0000,
    status VARCHAR(20) NOT NULL DEFAULT 'confirmed',
    tags JSON NULL,
    note TEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (event_id),
    KEY idx_cn_macro_political_event_type_date (event_type, start_date),
    KEY idx_cn_macro_political_event_status (status),
    KEY idx_cn_macro_political_event_predicted (is_predicted, start_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
