CREATE TABLE IF NOT EXISTS market_index_weekly (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    trade_date DATE NOT NULL,
    index_code VARCHAR(20) NOT NULL,
    index_name VARCHAR(100),
    open DECIMAL(18,6),
    high DECIMAL(18,6),
    low DECIMAL(18,6),
    close DECIMAL(18,6),
    pre_close DECIMAL(18,6),
    pct_chg DECIMAL(18,6),
    volume DECIMAL(24,6),
    amount DECIMAL(24,6),
    currency VARCHAR(8) DEFAULT 'CNY',
    pct_chg_unit VARCHAR(20),
    volume_unit VARCHAR(20),
    amount_unit VARCHAR(20),
    period_start_date DATE,
    period_end_date DATE,
    data_source VARCHAR(100) NOT NULL,
    source_url TEXT,
    available_time DATETIME NOT NULL,
    crawl_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    raw_hash CHAR(64),
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_market_index_weekly (trade_date, index_code),
    KEY idx_market_index_weekly_code_date (index_code, trade_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS market_index_monthly (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    trade_date DATE NOT NULL,
    index_code VARCHAR(20) NOT NULL,
    index_name VARCHAR(100),
    open DECIMAL(18,6),
    high DECIMAL(18,6),
    low DECIMAL(18,6),
    close DECIMAL(18,6),
    pre_close DECIMAL(18,6),
    pct_chg DECIMAL(18,6),
    volume DECIMAL(24,6),
    amount DECIMAL(24,6),
    currency VARCHAR(8) DEFAULT 'CNY',
    pct_chg_unit VARCHAR(20),
    volume_unit VARCHAR(20),
    amount_unit VARCHAR(20),
    period_start_date DATE,
    period_end_date DATE,
    data_source VARCHAR(100) NOT NULL,
    source_url TEXT,
    available_time DATETIME NOT NULL,
    crawl_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    raw_hash CHAR(64),
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_market_index_monthly (trade_date, index_code),
    KEY idx_market_index_monthly_code_date (index_code, trade_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
