CREATE TABLE IF NOT EXISTS market_index_minute_raw (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    trade_time DATETIME NOT NULL,
    trade_date DATE NOT NULL,
    index_code VARCHAR(20) NOT NULL,
    ts_code VARCHAR(20) NOT NULL,
    index_name VARCHAR(100),
    freq VARCHAR(10) NOT NULL,
    open DECIMAL(18,6),
    high DECIMAL(18,6),
    low DECIMAL(18,6),
    close DECIMAL(18,6),
    volume DECIMAL(24,4),
    amount DECIMAL(24,4),
    currency VARCHAR(10) DEFAULT 'CNY',
    volume_unit VARCHAR(30) DEFAULT 'share',
    amount_unit VARCHAR(30) DEFAULT 'CNY_yuan',
    data_source VARCHAR(80) NOT NULL,
    source_url TEXT,
    available_time DATETIME NOT NULL,
    crawl_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    raw_hash CHAR(64),
    UNIQUE KEY uk_market_index_minute (index_code, trade_time, freq, data_source),
    KEY idx_market_index_minute_time (trade_time),
    KEY idx_market_index_minute_date (trade_date, index_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
