CREATE TABLE IF NOT EXISTS option_contract_daily_raw (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    trade_date DATE NOT NULL,
    underlying_code VARCHAR(20) NOT NULL,
    underlying_name VARCHAR(80) NOT NULL,
    option_market VARCHAR(40) NOT NULL,
    contract_code VARCHAR(40) NOT NULL,
    contract_month VARCHAR(12),
    option_side VARCHAR(8),
    strike_price DECIMAL(18,4),
    open DECIMAL(18,6),
    high DECIMAL(18,6),
    low DECIMAL(18,6),
    close DECIMAL(18,6),
    volume DECIMAL(24,4),
    amount DECIMAL(24,4),
    open_interest DECIMAL(24,4),
    data_source VARCHAR(80) NOT NULL,
    source_url TEXT,
    available_time DATETIME NOT NULL,
    crawl_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    raw_hash CHAR(64),
    UNIQUE KEY uk_option_contract_daily (trade_date, contract_code, data_source),
    KEY idx_option_contract_underlying_date (underlying_code, trade_date),
    KEY idx_option_contract_market_date (option_market, trade_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS option_qvix_daily_raw (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    trade_date DATE NOT NULL,
    underlying_code VARCHAR(20) NOT NULL,
    underlying_name VARCHAR(80) NOT NULL,
    option_market VARCHAR(40) NOT NULL,
    qvix_code VARCHAR(40) NOT NULL,
    open DECIMAL(18,6),
    high DECIMAL(18,6),
    low DECIMAL(18,6),
    close DECIMAL(18,6),
    data_source VARCHAR(80) NOT NULL,
    source_url TEXT,
    available_time DATETIME NOT NULL,
    crawl_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    raw_hash CHAR(64),
    UNIQUE KEY uk_option_qvix_daily (trade_date, qvix_code, data_source),
    KEY idx_option_qvix_underlying_date (underlying_code, trade_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
