CREATE TABLE IF NOT EXISTS market_index_daily (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    trade_date DATE NOT NULL,
    index_code VARCHAR(20) NOT NULL,
    index_name VARCHAR(50),
    open DECIMAL(18,4),
    high DECIMAL(18,4),
    low DECIMAL(18,4),
    close DECIMAL(18,4),
    pre_close DECIMAL(18,4),
    pct_chg DECIMAL(10,4),
    volume DECIMAL(20,4),
    amount DECIMAL(20,4),
    data_source VARCHAR(50),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_index_daily (trade_date, index_code),
    KEY idx_trade_date (trade_date),
    KEY idx_index_code (index_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS market_etf_daily (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    trade_date DATE NOT NULL,
    etf_code VARCHAR(20) NOT NULL,
    etf_name VARCHAR(100),
    open DECIMAL(18,4),
    high DECIMAL(18,4),
    low DECIMAL(18,4),
    close DECIMAL(18,4),
    pct_chg DECIMAL(10,4),
    volume DECIMAL(20,4),
    amount DECIMAL(20,4),
    turnover DECIMAL(10,4),
    data_source VARCHAR(50),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_etf_daily (trade_date, etf_code),
    KEY idx_trade_date (trade_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS market_futures_daily (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    trade_date DATE NOT NULL,
    future_code VARCHAR(30) NOT NULL,
    future_name VARCHAR(100),
    category VARCHAR(50),
    open DECIMAL(18,4),
    high DECIMAL(18,4),
    low DECIMAL(18,4),
    close DECIMAL(18,4),
    settle DECIMAL(18,4),
    pct_chg DECIMAL(10,4),
    volume DECIMAL(20,4),
    open_interest DECIMAL(20,4),
    amount DECIMAL(20,4),
    data_source VARCHAR(50),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_future_daily (trade_date, future_code),
    KEY idx_trade_date (trade_date),
    KEY idx_future_code (future_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS market_feature_daily (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    trade_date DATE NOT NULL,
    index_code VARCHAR(20) NOT NULL,
    ret_1d DECIMAL(12,6),
    ret_3d DECIMAL(12,6),
    ret_5d DECIMAL(12,6),
    ret_10d DECIMAL(12,6),
    ma5_gap DECIMAL(12,6),
    ma10_gap DECIMAL(12,6),
    ma20_gap DECIMAL(12,6),
    macd DECIMAL(12,6),
    macd_signal DECIMAL(12,6),
    macd_hist DECIMAL(12,6),
    rsi6 DECIMAL(12,6),
    rsi14 DECIMAL(12,6),
    atr14 DECIMAL(12,6),
    boll_width DECIMAL(12,6),
    amount_zscore_20d DECIMAL(12,6),
    volatility_10d DECIMAL(12,6),
    volatility_20d DECIMAL(12,6),
    relative_hs300 DECIMAL(12,6),
    relative_zz500 DECIMAL(12,6),
    relative_cyb DECIMAL(12,6),
    upper_shadow_ratio DECIMAL(12,6),
    lower_shadow_ratio DECIMAL(12,6),
    body_ratio DECIMAL(12,6),
    intraday_range DECIMAL(12,6),
    upper_probe DECIMAL(12,6),
    lower_probe DECIMAL(12,6),
    doji DECIMAL(12,6),
    long_upper_shadow DECIMAL(12,6),
    long_lower_shadow DECIMAL(12,6),
    heavy_upper_shadow DECIMAL(12,6),
    heavy_lower_shadow DECIMAL(12,6),
    gap_up DECIMAL(12,6),
    gap_down DECIMAL(12,6),
    large_range_day DECIMAL(12,6),
    macd_golden_cross DECIMAL(12,6),
    macd_dead_cross DECIMAL(12,6),
    macd_golden_cross_days DECIMAL(12,6),
    macd_dead_cross_days DECIMAL(12,6),
    macd_hist_turn_positive DECIMAL(12,6),
    macd_hist_turn_negative DECIMAL(12,6),
    kdj_k DECIMAL(12,6),
    kdj_d DECIMAL(12,6),
    kdj_j DECIMAL(12,6),
    kdj_k_minus_d DECIMAL(12,6),
    kdj_golden_cross DECIMAL(12,6),
    kdj_dead_cross DECIMAL(12,6),
    kdj_golden_cross_days DECIMAL(12,6),
    kdj_dead_cross_days DECIMAL(12,6),
    kdj_j_overbought DECIMAL(12,6),
    kdj_j_oversold DECIMAL(12,6),
    kdj_j_overbought_turn_down DECIMAL(12,6),
    expma12 DECIMAL(12,6),
    expma50 DECIMAL(12,6),
    expma12_gap DECIMAL(12,6),
    expma_golden_cross DECIMAL(12,6),
    expma_dead_cross DECIMAL(12,6),
    expma_golden_cross_days DECIMAL(12,6),
    expma_dead_cross_days DECIMAL(12,6),
    cci14 DECIMAL(12,6),
    cci14_overbought DECIMAL(12,6),
    cci14_turn_down DECIMAL(12,6),
    cci14_overbought_turn_down DECIMAL(12,6),
    wr14 DECIMAL(12,6),
    ma20_slope_5d DECIMAL(12,6),
    ma60_slope_10d DECIMAL(12,6),
    ma20_slope_5d_negative DECIMAL(12,6),
    ma60_slope_10d_negative DECIMAL(12,6),
    close_above_ma20 DECIMAL(12,6),
    close_above_ma60 DECIMAL(12,6),
    above_ma20_days DECIMAL(12,6),
    below_ma20_days DECIMAL(12,6),
    above_ma60_days DECIMAL(12,6),
    below_ma60_days DECIMAL(12,6),
    ma20_ma60_gap DECIMAL(12,6),
    drawdown_20d DECIMAL(12,6),
    drawdown_60d DECIMAL(12,6),
    volume_zscore_20d DECIMAL(12,6),
    volume_ratio_5d_20d DECIMAL(12,6),
    amount_percentile_60d DECIMAL(12,6),
    volume_percentile_60d DECIMAL(12,6),
    down_with_volume DECIMAL(12,6),
    up_with_volume DECIMAL(12,6),
    shrink_rebound DECIMAL(12,6),
    volatility_5d DECIMAL(12,6),
    volatility_expand DECIMAL(12,6),
    atr_expand DECIMAL(12,6),
    boll_lower_break DECIMAL(12,6),
    boll_upper_break DECIMAL(12,6),
    boll_band_position DECIMAL(12,6),
    regime_trend_score DECIMAL(12,6),
    is_bull_trend DECIMAL(12,6),
    is_bear_trend DECIMAL(12,6),
    regime_state_days DECIMAL(12,6),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_market_feature (trade_date, index_code),
    KEY idx_trade_date (trade_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sentiment_guba_raw (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    post_id VARCHAR(100),
    source VARCHAR(50),
    bar_name VARCHAR(100),
    publish_time DATETIME,
    trade_date DATE,
    title TEXT,
    content MEDIUMTEXT,
    read_count INT,
    comment_count INT,
    like_count INT,
    author VARCHAR(100),
    url TEXT,
    crawl_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uk_guba_post (post_id),
    KEY idx_trade_date (trade_date),
    KEY idx_bar_name (bar_name),
    KEY idx_publish_time (publish_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sentiment_guba_comment_raw (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    comment_id VARCHAR(160) NOT NULL,
    post_id VARCHAR(100) NOT NULL,
    source VARCHAR(50),
    bar_name VARCHAR(100),
    publish_time DATETIME,
    trade_date DATE,
    author VARCHAR(100),
    content MEDIUMTEXT,
    like_count INT,
    reply_count INT,
    url TEXT,
    crawl_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uk_guba_comment (comment_id),
    KEY idx_post_id (post_id),
    KEY idx_trade_date (trade_date),
    KEY idx_bar_name (bar_name),
    KEY idx_publish_time (publish_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS news_raw (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    news_id VARCHAR(160),
    source VARCHAR(50),
    publish_time DATETIME,
    trade_date DATE,
    title TEXT,
    content MEDIUMTEXT,
    url TEXT,
    matched_keywords TEXT,
    matched_groups TEXT,
    crawl_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uk_news_id (news_id),
    KEY idx_trade_date (trade_date),
    KEY idx_source (source),
    KEY idx_publish_time (publish_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sentiment_feature_daily (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    trade_date DATE NOT NULL,
    topic VARCHAR(100),
    source VARCHAR(50),
    post_count INT,
    comment_count INT,
    read_count BIGINT,
    heat_score DECIMAL(12,6),
    heat_zscore_20d DECIMAL(12,6),
    heat_zscore_60d DECIMAL(12,6),
    heat_change_3d DECIMAL(12,6),
    sentiment_score DECIMAL(12,6),
    positive_ratio DECIMAL(12,6),
    negative_ratio DECIMAL(12,6),
    disagreement DECIMAL(12,6),
    emotion_stage VARCHAR(50),
    top_keywords TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_sentiment_feature (trade_date, topic, source),
    KEY idx_trade_date (trade_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS event_daily (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    trade_date DATE NOT NULL,
    event_name VARCHAR(200),
    event_type VARCHAR(50),
    event_stage VARCHAR(50),
    expectation_level VARCHAR(50),
    surprise_level VARCHAR(50),
    affected_style VARCHAR(50),
    impact_direction VARCHAR(20),
    impact_strength INT,
    event_score DECIMAL(12,6),
    llm_reason TEXT,
    source_ids VARCHAR(500),
    matched_keywords TEXT,
    matched_groups TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_trade_date (trade_date),
    KEY idx_event_type (event_type),
    UNIQUE KEY uk_event_source (source_ids)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS model_dataset_daily (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    trade_date DATE NOT NULL,
    index_code VARCHAR(20) NOT NULL,
    feature_json JSON,
    future_ret_3d DECIMAL(12,6),
    future_ret_5d DECIMAL(12,6),
    future_ret_7d DECIMAL(12,6),
    label_3d VARCHAR(20),
    label_5d VARCHAR(20),
    buy_label_5d TINYINT,
    short_label_5d TINYINT,
    label_7d VARCHAR(20),
    buy_label_7d TINYINT,
    short_label_7d TINYINT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_model_dataset (trade_date, index_code),
    KEY idx_trade_date (trade_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS prediction_result (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    trade_date DATE NOT NULL,
    horizon INT NOT NULL,
    direction_pred VARCHAR(20),
    return_pred DECIMAL(12,6),
    return_low DECIMAL(12,6),
    return_high DECIMAL(12,6),
    confidence DECIMAL(12,6),
    tech_score DECIMAL(12,6),
    sentiment_score DECIMAL(12,6),
    event_score DECIMAL(12,6),
    similar_event_score DECIMAL(12,6),
    explanation TEXT,
    risk_warning TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_prediction (trade_date, horizon),
    KEY idx_trade_date (trade_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS buy_signal_daily (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    trade_date DATE NOT NULL,
    model_version VARCHAR(64) NOT NULL,
    feature_version VARCHAR(64) NOT NULL,
    model_tag VARCHAR(64) NOT NULL,
    horizon INT NOT NULL,
    causal_regime VARCHAR(16) NOT NULL,
    buy_proba DECIMAL(12,8) NOT NULL,
    buy_threshold DECIMAL(12,8) NOT NULL,
    direction VARCHAR(16) NOT NULL,
    signal_strength VARCHAR(16) NOT NULL,
    pred_ret DECIMAL(12,8) NULL,
    future_ret_7d DECIMAL(12,8) NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_buy_signal (trade_date, model_version, horizon),
    KEY idx_buy_signal_date (trade_date),
    KEY idx_buy_signal_direction (direction)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
